#pragma once
#define WINDOW_WIDTH 1024
#define WINDOW_HEIGHT 768
#define PARENT_WINDOW_WIDTH 800
#define PARENT_WINDOW_HEIGHT 600
#define PARENT_WINDOW_TITLE "The JetBook"
#define LEFT_PANE_WINDOW_WIDTH 200
#define LEFT_PANE_WINDOW_HEIGHT 600
#define CENTER_PANE_WINDOW_WIDTH 400
#define CENTER_PANE_WINDOW_HEIGHT 300
#define RIGHT_PANE_WINDOW_WIDTH 400
#define RIGHT_PANE_WINDOW_HEIGHT 300
#define CENTER_PANE_INDENT 3
#define NUM_COLUMNS 2