#pragma once
#define WINDOW_WIDTH 1024
#define WINDOW_HEIGHT 768
#define CHILD_ROUNDING 1.0f
#define FRAME_ROUNDING 1.0f
#define WINDOW_MENU_BUTTON -1 //-1 for no button, 0 for left aligned, 1 for right aligned
#define WINDOW_TITLE_ALIGN 0.50f
#define WINDOW_SAFE_AREA_PADDING 30.0f
#define PARENT_WINDOW_WIDTH 800
#define PARENT_WINDOW_HEIGHT 600
#define PARENT_WINDOW_TITLE "The JetBook"
#define LEFT_PANE_WINDOW_WIDTH 200
#define LEFT_PANE_WINDOW_HEIGHT 600
#define CENTER_PANE_WINDOW_WIDTH 400
#define CENTER_PANE_WINDOW_HEIGHT 300
#define RIGHT_PANE_WINDOW_WIDTH 400
#define RIGHT_PANE_WINDOW_HEIGHT 300
#define RIGHT_PANE_PARENT_HEADER "Details"
#define RIGHT_PANE_INDENT 70
#define CENTER_PANE_INDENT 3
#define NUM_COLUMNS 2